dojo.provide("dijit.nls.dijit-all_tr");
dojo.provide("dojo.nls.colors");
dojo.nls.colors._built = true;
dojo.provide("dojo.nls.colors.tr");
dojo.nls.colors.tr = {
    "lightsteelblue": "açık metalik mavi",
    "orangered": "turuncu kırmızı",
    "midnightblue": "gece mavisi",
    "cadetblue": "denizci mavisi",
    "seashell": "deniz kabuğu",
    "slategrey": "arduvaz grisi",
    "coral": "mercan",
    "darkturquoise": "koyu turkuaz",
    "antiquewhite": "antik beyaz",
    "mediumspringgreen": "orta bahar yeşili",
    "salmon": "somon",
    "darkgrey": "koyu gri",
    "ivory": "fildişi",
    "greenyellow": "yeşil-sarı",
    "mistyrose": "gülkurusu",
    "lightsalmon": "açık somon",
    "silver": "gümüş",
    "dimgrey": "soluk gri",
    "orange": "turuncu",
    "white": "beyaz",
    "navajowhite": "navajo beyazı",
    "royalblue": "parlak koyu mavi",
    "deeppink": "koyu pembe",
    "lime": "limon yeşili",
    "oldlace": "eski dantel",
    "chartreuse": "chartreuse",
    "darkcyan": "koyu camgöbeği",
    "yellow": "sarı",
    "linen": "keten",
    "olive": "zeytin",
    "gold": "altın",
    "lawngreen": "çimen yeşili",
    "lightyellow": "açık sarı",
    "tan": "güneş yanığı",
    "darkviolet": "koyu eflatun",
    "lightslategrey": "açık arduvaz grisi",
    "grey": "gri",
    "darkkhaki": "koyu haki",
    "green": "yeşil",
    "deepskyblue": "koyu gök mavisi",
    "aqua": "deniz mavisi",
    "sienna": "koyu kahve",
    "mintcream": "naneli krem",
    "rosybrown": "pembemsi kahverengi",
    "mediumslateblue": "orta arduvaz mavisi",
    "magenta": "macenta",
    "lightseagreen": "açık deniz yeşili",
    "cyan": "camgöbeği",
    "olivedrab": "asker yeşili",
    "darkgoldenrod": "koyu sarı",
    "slateblue": "arduvaz mavisi",
    "mediumaquamarine": "orta akuamarin",
    "lavender": "lavanta",
    "mediumseagreen": "orta deniz yeşili",
    "maroon": "kestane",
    "darkslategray": "koyu arduvaz grisi",
    "mediumturquoise": "orta turkuaz",
    "ghostwhite": "silik beyaz",
    "darkblue": "koyu mavi",
    "mediumvioletred": "orta menekşe kırmızısı",
    "brown": "kahverengi",
    "lightgray": "açık gri",
    "sandybrown": "kum rengi",
    "pink": "pembe",
    "firebrick": "canlı kiremit",
    "indigo": "çivit mavisi",
    "snow": "kar",
    "darkorchid": "koyu orkide",
    "turquoise": "turkuaz",
    "chocolate": "çikolata",
    "springgreen": "bahar yeşili",
    "moccasin": "mokosen",
    "navy": "lacivert",
    "lemonchiffon": "limoni",
    "teal": "Teal mavi",
    "floralwhite": "çiçek beyazı",
    "cornflowerblue": "peygamber çiçeği mavisi",
    "paleturquoise": "soluk turkuaz",
    "purple": "mor",
    "gainsboro": "gainsboro",
    "plum": "erik",
    "red": "kırmızı",
    "blue": "mavi",
    "forestgreen": "koyu deniz yeşili",
    "darkgreen": "koyu yeşil",
    "honeydew": "çam sakızı",
    "darkseagreen": "koyu deniz yeşili",
    "lightcoral": "açık mercan",
    "palevioletred": "soluk menekşe kırmızısı",
    "mediumpurple": "orta mor",
    "saddlebrown": "açık kahve",
    "darkmagenta": "koyu mor",
    "thistle": "devedikeni",
    "whitesmoke": "beyaz duman",
    "wheat": "buğday",
    "violet": "eflatun",
    "lightskyblue": "açık gök mavisi",
    "goldenrod": "sarısabır",
    "mediumblue": "orta mavi",
    "skyblue": "gök mavisi",
    "crimson": "crimson",
    "darksalmon": "koyu somon",
    "darkred": "koyu kırmızı",
    "darkslategrey": "koyu arduvaz grisi",
    "peru": "peru",
    "lightgrey": "açık gri",
    "lightgoldenrodyellow": "açık sarısabır",
    "blanchedalmond": "soluk badem",
    "aliceblue": "alice mavisi",
    "bisque": "bisküvi",
    "slategray": "arduvaz grisi",
    "palegoldenrod": "soluk sarısabır",
    "darkorange": "koyu turuncu",
    "aquamarine": "akuamarin",
    "lightgreen": "açık yeşil",
    "burlywood": "sarımsı kahverengi",
    "dodgerblue": "toz mavisi",
    "darkgray": "koyu gri",
    "lightcyan": "açık camgöbeği",
    "powderblue": "pudra mavisi",
    "blueviolet": "mavi-mor",
    "orchid": "orkide",
    "dimgray": "soluk gri",
    "beige": "bej",
    "fuchsia": "fuşya",
    "lavenderblush": "lavanta pembesi",
    "hotpink": "sıcak pembe",
    "steelblue": "metalik mavi",
    "tomato": "domates",
    "lightpink": "açık pembe",
    "limegreen": "küf yeşili",
    "indianred": "kızılderili kırmızısı",
    "papayawhip": "papaya sapı",
    "lightslategray": "açık arduvaz grisi",
    "gray": "gri",
    "mediumorchid": "orta orkide",
    "cornsilk": "mısır rengi",
    "black": "siyah",
    "seagreen": "deniz yeşili",
    "darkslateblue": "koyu arduvaz mavisi",
    "khaki": "haki",
    "lightblue": "açık mavi",
    "palegreen": "soluk yeşil",
    "azure": "azur mavisi",
    "peachpuff": "açık şeftali",
    "darkolivegreen": "koyu zeytin yeşili",
    "yellowgreen": "sarı yeşil"
};
dojo.provide("dijit.nls.loading");
dijit.nls.loading._built = true;
dojo.provide("dijit.nls.loading.tr");
dijit.nls.loading.tr = {"loadingState": "Yükleniyor...", "errorState": "Üzgünüz, bir hata oluştu"};
dojo.provide("dijit.nls.common");
dijit.nls.common._built = true;
dojo.provide("dijit.nls.common.tr");
dijit.nls.common.tr = {"buttonOk": "Tamam", "buttonCancel": "İptal", "buttonSave": "Kaydet", "itemClose": "Kapat"};
dojo.provide("dijit._editor.nls.commands");
dijit._editor.nls.commands._built = true;
dojo.provide("dijit._editor.nls.commands.tr");
dijit._editor.nls.commands.tr = {
    "removeFormat": "Biçimi Kaldır",
    "copy": "Kopyala",
    "paste": "Yapıştır",
    "selectAll": "Tümünü Seç",
    "insertOrderedList": "Numaralı Liste",
    "insertTable": "Tablo Ekle/Düzenle",
    "print": "Yazdır",
    "underline": "Altı Çizili",
    "foreColor": "Ön Plan Rengi",
    "htmlToggle": "HTML Kaynağı",
    "formatBlock": "Paragraf Stili",
    "newPage": "Yeni Sayfa",
    "insertHorizontalRule": "Yatay Kural",
    "delete": "Sil",
    "insertUnorderedList": "Madde İşaretli Liste",
    "tableProp": "Tablo Özelliği",
    "insertImage": "Resim Ekle",
    "superscript": "Üst Simge",
    "subscript": "Alt Simge",
    "createLink": "Bağlantı Oluştur",
    "undo": "Geri Al",
    "fullScreen": "Tam Ekranı Aç/Kapat",
    "italic": "İtalik",
    "fontName": "Yazı Tipi Adı",
    "justifyLeft": "Sola Hizala",
    "unlink": "Bağlantıyı Kaldır",
    "toggleTableBorder": "Tablo Kenarlığını Göster/Gizle",
    "viewSource": "HTML Kaynağını Görüntüle",
    "fontSize": "Yazı Tipi Boyutu",
    "systemShortcut": "\"${0}\" işlemi yalnızca tarayıcınızda bir klavye kısayoluyla birlikte kullanılabilir. Şunu kullanın: ${1}.",
    "indent": "Girinti",
    "redo": "Yinele",
    "strikethrough": "Üstü Çizili",
    "justifyFull": "Yasla",
    "justifyCenter": "Ortaya Hizala",
    "hiliteColor": "Arka Plan Rengi",
    "deleteTable": "Tabloyu Sil",
    "outdent": "Çıkıntı",
    "cut": "Kes",
    "plainFormatBlock": "Paragraf Stili",
    "toggleDir": "Yönü Değiştir",
    "bold": "Kalın",
    "tabIndent": "Sekme Girintisi",
    "justifyRight": "Sağa Hizala",
    "appleKey": "⌘${0}",
    "ctrlKey": "ctrl+${0}"
};
dojo.provide("dijit.form.nls.validate");
dijit.form.nls.validate._built = true;
dojo.provide("dijit.form.nls.validate.tr");
dijit.form.nls.validate.tr = {
    "rangeMessage": "Bu değer aralık dışında.",
    "invalidMessage": "Girilen değer geçersiz.",
    "missingMessage": "Bu değer gerekli."
};
dojo.provide("dijit.form.nls.ComboBox");
dijit.form.nls.ComboBox._built = true;
dojo.provide("dijit.form.nls.ComboBox.tr");
dijit.form.nls.ComboBox.tr = {"previousMessage": "Önceki seçenekler", "nextMessage": "Diğer seçenekler"};
dojo.provide("dijit._editor.nls.FontChoice");
dijit._editor.nls.FontChoice._built = true;
dojo.provide("dijit._editor.nls.FontChoice.tr");
dijit._editor.nls.FontChoice.tr = {
    "1": "xx-küçük",
    "2": "x-küçük",
    "formatBlock": "Biçim",
    "3": "küçük",
    "4": "orta",
    "5": "büyük",
    "6": "x-büyük",
    "7": "xx-büyük",
    "fantasy": "fantazi",
    "serif": "serif",
    "p": "Paragraf",
    "pre": "Önceden Biçimlendirilmiş",
    "sans-serif": "sans-serif",
    "fontName": "Yazı Tipi",
    "h1": "Başlık",
    "h2": "Alt Başlık",
    "h3": "Alt Alt Başlık",
    "monospace": "tek aralıklı",
    "fontSize": "Boyut",
    "cursive": "el yazısı",
    "noFormat": "None"
};
dojo.provide("dijit._editor.nls.LinkDialog");
dijit._editor.nls.LinkDialog._built = true;
dojo.provide("dijit._editor.nls.LinkDialog.tr");
dijit._editor.nls.LinkDialog.tr = {
    "text": "Açıklama:",
    "insertImageTitle": "Resim Özellikleri",
    "set": "Ayarla",
    "newWindow": "Yeni Pencere",
    "topWindow": "En Üst Pencere",
    "target": "Hedef:",
    "createLinkTitle": "Bağlantı Özellikleri",
    "parentWindow": "Üst Pencere",
    "currentWindow": "Geçerli Pencere",
    "url": "URL:"
};
dojo.provide("dojo.cldr.nls.number");
dojo.cldr.nls.number._built = true;
dojo.provide("dojo.cldr.nls.number.tr");
dojo.cldr.nls.number.tr = {
    "group": ".",
    "percentSign": "%",
    "exponential": "E",
    "percentFormat": "% #,##0",
    "scientificFormat": "#E0",
    "list": ";",
    "infinity": "∞",
    "patternDigit": "#",
    "minusSign": "-",
    "decimal": ",",
    "nan": "NaN",
    "nativeZeroDigit": "0",
    "perMille": "‰",
    "decimalFormat": "#,##0.###",
    "currencyFormat": "#,##0.00 ¤",
    "plusSign": "+",
    "currencySpacing-afterCurrency-currencyMatch": "[:letter:]",
    "currencySpacing-beforeCurrency-surroundingMatch": "[:digit:]",
    "currencySpacing-afterCurrency-insertBetween": " ",
    "currencySpacing-afterCurrency-surroundingMatch": "[:digit:]",
    "currencySpacing-beforeCurrency-currencyMatch": "[:letter:]",
    "currencySpacing-beforeCurrency-insertBetween": " "
};
dojo.provide("dojo.cldr.nls.currency");
dojo.cldr.nls.currency._built = true;
dojo.provide("dojo.cldr.nls.currency.tr");
dojo.cldr.nls.currency.tr = {
    "HKD_displayName": "Hong Kong Doları",
    "CHF_displayName": "İsviçre Frangı",
    "JPY_symbol": "¥",
    "CAD_displayName": "Kanada Doları",
    "CNY_displayName": "Çin Yuanı Renminbi",
    "USD_symbol": "$",
    "AUD_displayName": "Avustralya Doları",
    "JPY_displayName": "Japon Yeni",
    "USD_displayName": "ABD Doları",
    "GBP_displayName": "İngiliz Sterlini",
    "EUR_displayName": "Euro",
    "CAD_symbol": "CA$",
    "GBP_symbol": "£",
    "HKD_symbol": "HK$",
    "AUD_symbol": "AU$",
    "CNY_symbol": "CN¥",
    "EUR_symbol": "€"
};
dojo.provide("dojo.cldr.nls.gregorian");
dojo.cldr.nls.gregorian._built = true;
dojo.provide("dojo.cldr.nls.gregorian.tr");
dojo.cldr.nls.gregorian.tr = {
    "months-format-narrow": ["O", "Ş", "M", "N", "M", "H", "T", "A", "E", "E", "K", "A"],
    "field-weekday": "Haftanın Günü",
    "dateFormatItem-yyQQQQ": "QQQQ yy",
    "dateFormatItem-yQQQ": "QQQ y",
    "dateFormatItem-yMEd": "dd.MM.yyyy EEE",
    "dateFormatItem-MMMEd": "dd MMM E",
    "eraNarrow": ["MÖ", "MS"],
    "dateFormat-long": "dd MMMM y",
    "months-format-wide": ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    "dateFormatItem-EEEd": "d EEE",
    "dayPeriods-format-wide-pm": "PM",
    "dateFormat-full": "dd MMMM y EEEE",
    "dateFormatItem-Md": "dd/MM",
    "field-era": "Miladi Dönem",
    "dateFormatItem-yM": "M/yyyy",
    "months-standAlone-wide": ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    "timeFormat-short": "HH:mm",
    "quarters-format-wide": ["1. çeyrek", "2. çeyrek", "3. çeyrek", "4. çeyrek"],
    "timeFormat-long": "HH:mm:ss z",
    "field-year": "Yıl",
    "dateFormatItem-yMMM": "MMM y",
    "dateFormatItem-yQ": "Q yyyy",
    "field-hour": "Saat",
    "months-format-abbr": ["Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"],
    "dateFormatItem-yyQ": "Q yy",
    "timeFormat-full": "HH:mm:ss zzzz",
    "field-day-relative+0": "Bugün",
    "field-day-relative+1": "Yarın",
    "field-day-relative+2": "Yarından sonraki gün",
    "dateFormatItem-H": "HH",
    "field-day-relative+3": "Üç gün sonra",
    "months-standAlone-abbr": ["Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"],
    "quarters-format-abbr": ["Ç1", "Ç2", "Ç3", "Ç4"],
    "quarters-standAlone-wide": ["1. çeyrek", "2. çeyrek", "3. çeyrek", "4. çeyrek"],
    "dateFormatItem-M": "L",
    "days-standAlone-wide": ["Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi"],
    "dateFormatItem-MMMMd": "dd MMMM",
    "dateFormatItem-yyMMM": "MMM yy",
    "timeFormat-medium": "HH:mm:ss",
    "dateFormatItem-Hm": "HH:mm",
    "quarters-standAlone-abbr": ["Ç1", "Ç2", "Ç3", "Ç4"],
    "eraAbbr": ["MÖ", "MS"],
    "field-minute": "Dakika",
    "field-dayperiod": "AM/PM",
    "days-standAlone-abbr": ["Paz", "Pzt", "Sal", "Çar", "Per", "Cum", "Cmt"],
    "dateFormatItem-d": "d",
    "dateFormatItem-ms": "mm:ss",
    "field-day-relative+-1": "Dün",
    "field-day-relative+-2": "Evvelsi gün",
    "field-day-relative+-3": "Üç gün önce",
    "dateFormatItem-MMMd": "dd MMM",
    "dateFormatItem-MEd": "dd/MM E",
    "dateFormatItem-yMMMM": "MMMM y",
    "field-day": "Gün",
    "days-format-wide": ["Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi"],
    "field-zone": "Saat Dilimi",
    "dateFormatItem-y": "y",
    "months-standAlone-narrow": ["O", "Ş", "M", "N", "M", "H", "T", "A", "E", "E", "K", "A"],
    "dateFormatItem-yyMM": "MM/yy",
    "dateFormatItem-hm": "h:mm a",
    "days-format-abbr": ["Paz", "Pzt", "Sal", "Çar", "Per", "Cum", "Cmt"],
    "eraNames": ["Milattan Önce", "Milattan Sonra"],
    "days-format-narrow": ["P", "P", "S", "Ç", "P", "C", "C"],
    "field-month": "Ay",
    "days-standAlone-narrow": ["P", "P", "S", "Ç", "P", "C", "C"],
    "dateFormatItem-MMM": "LLL",
    "dayPeriods-format-wide-am": "AM",
    "dateFormatItem-MMMMEd": "dd MMMM E",
    "dateFormat-short": "dd.MM.yyyy",
    "field-second": "Saniye",
    "dateFormatItem-yMMMEd": "dd MMM y EEE",
    "dateFormatItem-Ed": "d E",
    "field-week": "Hafta",
    "dateFormat-medium": "dd MMM y",
    "dateFormatItem-mmss": "mm:ss",
    "dateFormatItem-Hms": "HH:mm:ss",
    "dateFormatItem-hms": "h:mm:ss a",
    "dateFormatItem-yyyy": "y",
    "quarters-standAlone-narrow": ["1", "2", "3", "4"],
    "dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}",
    "dateTimeFormat-medium": "{1} {0}",
    "dayPeriods-format-abbr-am": "AM",
    "dateTimeFormats-appendItem-Second": "{0} ({2}: {1})",
    "dateTimeFormats-appendItem-Era": "{0} {1}",
    "dateTimeFormats-appendItem-Week": "{0} ({2}: {1})",
    "quarters-format-narrow": ["1", "2", "3", "4"],
    "dateFormatItem-h": "h a",
    "dateTimeFormat-long": "{1} {0}",
    "dayPeriods-format-narrow-am": "AM",
    "dateTimeFormat-full": "{1} {0}",
    "dateTimeFormats-appendItem-Day": "{0} ({2}: {1})",
    "dateTimeFormats-appendItem-Year": "{0} {1}",
    "dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})",
    "dayPeriods-format-abbr-pm": "PM",
    "dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})",
    "dateTimeFormats-appendItem-Month": "{0} ({2}: {1})",
    "dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})",
    "dateTimeFormats-appendItem-Timezone": "{0} {1}",
    "dayPeriods-format-narrow-pm": "PM",
    "dateTimeFormat-short": "{1} {0}"
};
