--------------------------------------------------------
--  Fichier créé - vendredi-septembre-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEMANDES
--------------------------------------------------------

  CREATE TABLE "PRODUITS_DERIVES"."DEMANDES" 
   (	"ID" NUMBER, 
	"ILN" NUMBER(*,0), 
	"COORDINATEUR" VARCHAR2(10 BYTE), 
	"RCR" VARCHAR2(9 BYTE), 
	"FORMATFINAL" VARCHAR2(3 BYTE), 
	"ETAT_EXTRACTED" CHAR(1 BYTE), 
	"ETAT_CLEANED" CHAR(1 BYTE), 
	"ETAT_GROUPED" CHAR(1 BYTE), 
	"ETAT_FILTERED" CHAR(1 BYTE), 
	"EXCEPTIONMSG" VARCHAR2(4000 BYTE), 
	"DATEEXTRACTION" DATE, 
	"NBNOTICES" NUMBER, 
	"AVECCOLLECTIONS" CHAR(1 BYTE), 
	"ETAT_SORTED" CHAR(1 BYTE), 
	"ETAT_XHTML" CHAR(1 BYTE), 
	"ETAT_PDF" CHAR(1 BYTE), 
	"ETAT_RTF" CHAR(1 BYTE), 
	"ETAT_SLK" CHAR(1 BYTE), 
	"EXCLUDEDDATAFIELDS" VARCHAR2(60 BYTE), 
	"LAYOUT" VARCHAR2(60 BYTE), 
	"MD5HASH" VARCHAR2(32 BYTE), 
	"BYTESLENGTH" NUMBER, 
	"LOW_LIMIT" NUMBER(*,0), 
	"HIGH_LIMIT" NUMBER(*,0), 
	"RCR_SHORTNAME" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUITS_DERIVES" ;
--------------------------------------------------------
--  DDL for Index DEMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRODUITS_DERIVES"."DEMANDES_PK" ON "PRODUITS_DERIVES"."DEMANDES" ("FORMATFINAL", "ID", "RCR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUITS_DERIVES" ;
--------------------------------------------------------
--  Constraints for Table DEMANDES
--------------------------------------------------------

  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" MODIFY ("ILN" NOT NULL ENABLE);
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" MODIFY ("COORDINATEUR" NOT NULL ENABLE);
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" MODIFY ("RCR" NOT NULL ENABLE);
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" MODIFY ("FORMATFINAL" NOT NULL ENABLE);
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" MODIFY ("AVECCOLLECTIONS" NOT NULL ENABLE);
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" ADD CHECK (AVECCOLLECTIONS in (0,1)) ENABLE;
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" ADD CHECK ("ETAT_EXTRACTED"='W' OR "ETAT_EXTRACTED"='O' OR "ETAT_EXTRACTED"='X') ENABLE;
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" ADD CHECK (FORMATFINAL in ('pdf','rtf','slk')) ENABLE;
  ALTER TABLE "PRODUITS_DERIVES"."DEMANDES" ADD CONSTRAINT "DEMANDES_PK" PRIMARY KEY ("FORMATFINAL", "ID", "RCR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUITS_DERIVES"  ENABLE;
