name: "build-test-pubtodockerhub"

env:
  DOCKERHUB_IMAGE_PREFIX: abesesr/selfsudoc

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.properties'
  workflow_dispatch:


jobs:
  build-test-pubtodockerhub:
    runs-on: ubuntu-latest
    steps:

      - name: "Build: checkout source code"
        uses: actions/checkout@v6

      - name: "Push: prepare version from git tags/branchs"
        id: docker_tag_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE_PREFIX }}
          flavor: |
            latest=auto
            suffix=-batch
