name: "on-push-batch-changes"

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.properties'
      - 'ExportsLibreService/**'
  workflow_dispatch:

jobs:
  on-push-batch-changes:
    uses: ./.github/workflows/build-pubtodockerhub.yml
    with:
      target: batch
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
