name: "on-push-batch-changes"

on:
  push:
    paths:
      - 'Dockerfile'
      - 'Utils/**'
      - 'Connection/**'
      - 'Extract/**'
      - 'iText-src-5.0.2/**'
      - 'iTextRenderer/**'
      - 'Renderer/**'
      - 'Technic/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  on-push-batch-changes:
    uses: ./.github/workflows/build-pubtodockerhub.yml
    with:
      target: batch
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
