name: "on-push-web-changes"

on:
  push:
    paths:
      - 'ExportsLibreService/**'
      - 'Utils/**'
      - 'Connection/**'
  workflow_dispatch:

jobs:
  on-push-web-changes:
    uses: "./.github/workflows/build-pubtodockerhub.yml"
    with:
      target: front
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
